### ISSUE TITLE
Publish 0.3.0 to npm

### ISSUE THREAD

**Issue by arvindr21** [genomejs/gql#1]
@contra can you please push 0.3.0 to NPM? Looks like `and` operation is not available in 0.2.0.

Thanks.

**Comment by contra** [comment]
0.4.0 pushed

**Comment by arvindr21** [comment]
Thanks @contra.

Wanted to know, if I can add more genosets to the Genome project. Also wanted to create a Yeoman/Slush generator as well. Your thoughts?

Thanks.

**Comment by contra** [comment]
@arvindr21 

Generators: go for it
genosets: You want them on the genomejs page? There isn't really any reason for that, you can publish your own and add the genoset keyword on npm

**Comment by arvindr21** [comment]
Great! I was planning to add it as part of this organization, genoset keyword also works!

QQ on the genoset testing, for a given GS, I am sure we do not have enough test data to validate a given case, so how do we approach it?

And is there any GS Criteria to GQL mapping documentation? I tried to create a Genoset for Female using : http://www.snpedia.com/index.php/Gs145/criteria but could not as I was not sure how to represent 

```
or(rs2032651(-;-),
        atleast(3,
      rs1034428(A;G), 
...
```

in GQL. 

Tried this 

```js
var query = gql.query();
var q1 = gql.query();
var q2 = gql.query();

q1.exists("rs2032651");

q2.needs(3);
q2.exact("rs1034428", "AG");
q2.exact("rs10521792", "AG");
// snipp

query.or(q1, q2);

var genoStream = query.stream();
```

and it did not work.

Thanks.

**Comment by contra** [comment]
Yeah there are some cases that can't be expressed in GQL yet, still figuring out how to do those. Mainly nesting of conditions is tricky right now. I'm totally open to scrapping what I have and rewriting it differently if you have any better syntax ideas

**Comment by arvindr21** [comment]
Perfect. Thanks! I will go through the same get back to you!

Thanks for creating a platform like this to explore @contra  :)

**Comment by contra** [comment]
I was thinking about redoing it as a JSON thing or just writing a parser for the existing GQL format

**Comment by arvindr21** [comment]
Ok, You may be a better judge here.
