### ISSUE TITLE
naming conventions

### ISSUE THREAD

**Issue by pvjones** [genomejs/gql#11]
I've started putting together a curated collection of interesting genosets and SNPs ([located here](https://github.com/pvjones/gql_queries)). If possible, I'd like to make this useful for others in the community.

SNPedia uses the 'genoset' nomenclature for combinations of SNPs. It seems like this is usually used for gql queries, naming them 'gs103', 'gs159', etc. Are there any conventions in the genomeJS community for naming gql queries that refer to a single SNP? There are many interesting ones, such as the much-discussed "warrior vs. worrier" SNP, [rs4680](https://www.snpedia.com/index.php/Rs4680). This simply checks for hetero- or homozygosity at a single location. So far I've just been naming these according to their dbSNP number. But is there a better way? 

Another (hopefully related) question: some of these tests would really be conveniently suited for some sort of trinary output (there might be distinct 'meanings' for homozygous A, homozygous G, or heterozygous). Has anyone discussed alternative output formats compared to simple boolean? Or is the best approach to have three separate boolean-output gql queries--i.e. 'rs4680AA', 'rs4680GG', and 'rs4680AG'?

Thanks for bearing with my pedantic questions!

**Comment by contra** [comment]
I usually name the module something informative, and tag it with the RS or Genoset ID

**Comment by pvjones** [comment]
Great, thanks!
