### ISSUE TITLE
Meaning of `-` in gs syntax

### ISSUE THREAD

**Issue by mathiasbynens** [genomejs/gql#4]
I assume `rs2032651(-;-)` translates to `exists(…)`, and `rs2032651(-;A)` to `has(…, 'A')`. Would be nice to have this confirmed fo sho/documented somehow.
## TODO: document what these translate to
- [ ] `(;)`
- [ ] `(;-;)`
- [ ] `(;-A)`
- [ ] `(A;-)`
- [ ] `(D;D)`

**Comment by contra** [comment]
These are the docs for the genoset syntax from SNPedia http://www.snpedia.com/index.php/Criteria_syntax

**Comment by mathiasbynens** [comment]
Thanks for the link. I’ve asked here: http://www.snpedia.com/index.php/Talk:Criteria_syntax

**Comment by mathiasbynens** [comment]
> it should indicate a deletion, consistent with the notation shown at <https://www.biostars.org/p/84686/>, however I've increasingly been favoring `(;)` instead of `(-;-)`, and 23andMe notation has long forced us to also consider `(D;D)`. It would be good to get it consolidated and unified, but I've not done that yet. --- cariaso 21:59, 24 March 2015 (UTC)

**Comment by mathiasbynens** [comment]
Related question: are `(;-A)` and `(A;-)` equivalent?

**Comment by contra** [comment]
@mathiasbynens We should get some people from that project's GH info so we can consolidate discussion here. Would you mind asking if they use github or linking to this issue?

**Comment by mathiasbynens** [comment]
Done.

**Comment by cariaso** [comment]
> are (;-A) and (A;-) equivalent?
presumably you mean  
are (-;A) and (A;-) equivalent?
and the answer is yes.

**Comment by mathiasbynens** [comment]
Comparing http://www.snpedia.com/index.php/Gs144/criteria with https://github.com/genomejs/genoset-male/blob/master/index.js, it seems e.g. `rs2032651(D;D)` translates to `gql.exact('D')`, and not `gql.exact('DD')` like I’d expect. This confuses me slightly, but then again I’m not a biologist so I might be missing something basic here.

Adding a simple conversion table to the README would greatly help DNA n00bs like myself.

| GS notation   | `gql` notation               |
|---------------|------------------------------|
| `rs1234(X;X)` | `gql.exact('rs1234', 'X')`   |
| `rs1234(X)`   | `gql.has('rs1234', 'X')`     |
| `rs1234(-;X)  | `gql.has('rs1234', 'X')`???  |
| `rs1234(X;-)  | `gql.has('rs1234', 'X')`???  |
| `rs1234(-;-)  | `gql.exists('rs1234')`???    |
| `rs1234(;)    | `gql.exists('rs1234')`???    |
| `rs1234(D;D)  | ???                          |

Can anyone fill in the blanks?

**Comment by contra** [comment]
@mathiasbynens or I made a mistake when translating it :question: I think D;D could possibly be `gql.exact('DD')` 

@cariaso Any info? Is there anyone else we can ping who writes the genosets who would know more of the meaning behind these?

**Comment by cariaso** [comment]
23andMe indicates deletions with 'D'. Other groups use other standards. VCF does something completely stupid.  Someone homozygous for the deletion would be rs1234(D;D) in genoset notation. That might also be represented as rs1234(;) or rs1234(-;-). This is more an evolved solution than a plan. I have no information to interpret gql.exact('DD').

**Comment by contra** [comment]
Ah interesting, so we might need to do something when parsing 23AndMe files to switch that to a standardized value, then the genosets need to be updated so `D;D` = `-;-`

**Comment by mathiasbynens** [comment]
@cariaso clears this up here over at <http://www.snpedia.com/index.php/Talk:Rs6625163>:

> Yes, you can treat `Rs6625163(A)` as equivalent to `Rs6625163(A;A)`. However I'm gradually settling on the idea that `rs1234(A;A)` should be read as "at position rs1234 there are only A genotypes".

**Comment by mathiasbynens** [comment]
@contra So we should probably make `.exact('A')` equivalent to `.exact('A')`, or add a new API `.only('A')` (to avoid having to use `.or()` everywhere).

**Comment by contra** [comment]
Looking into some of these other ones now

**Comment by contra** [comment]
Also, dna2json has been updated so DD is accurately reflected as a deletion for 23andme data

**Comment by contra** [comment]
https://github.com/genomejs/dna2json/blob/master/lib/parsers/23andMe.js#L13
